### ISSUE TITLE
编译出错 android设备

### ISSUE THREAD

**Issue by wangfangc** [attentiveness/reading#50]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:prepareReadingRCTWeChatUnspecifiedLibrary'.
> Could not copy zip entry E:\WorkSpace\Studio_space_Test\ReactNativeDemo\readin
g-master1\reading-master\node_modules\react-native-wechat\android\build\outputs\
aar\RCTWeChat-release.aar!res/ to 'E:\WorkSpace\Studio_space_Test\ReactNativeDem
o\reading-master1\reading-master\android\app\build\intermediates\exploded-aar\re
ading\RCTWeChat\unspecified\res'.

**Comment by Richard-Cao** [comment]
clean完了重新build试试呢？我编译没问题，CI编译也没问题，你可以直接看reading的CI编译结果。

**Comment by wangfangc** [comment]
我重新clone 一下到新的目录里面可以编译成功、安装成功。但是在启动页面启动加载资源的时候又有新的问题了
 Unknown named module: './qiniu/auth/digest.js'

12-02 14:36:44.364 16332-16332/com.reading I/ViewRootImpl: CPU Rendering VSync enable = true
12-02 14:36:44.655 16332-19266/com.reading E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
12-02 14:36:44.664 16332-19266/com.reading W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
12-02 14:36:44.664 16332-19266/com.reading W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {6ca3362} sending message to a Handler on a dead thread
                                                           java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {6ca3362} sending message to a Handler on a dead thread
                                                               at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                               at android.os.Handler.enqueueMessage(Handler.java:631)
                                                               at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                               at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                               at android.os.Handler.post(Handler.java:326)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                               at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                               at java.lang.Thread.run(Thread.java:818)
12-02 14:36:44.666 16332-19266/com.reading W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
12-02 14:36:44.667 16332-19266/com.reading W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {6ca3362} sending message to a Handler on a dead thread
                                                           java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {6ca3362} sending message to a Handler on a dead thread
                                                               at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                               at android.os.Handler.enqueueMessage(Handler.java:631)
                                                               at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                               at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                               at android.os.Handler.post(Handler.java:326)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                               at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                               at java.lang.Thread.run(Thread.java:818)
12-02 14:36:44.716 16332-16332/com.reading W/unknown:React: Packager connection already open, nooping.
                                                            
                                                            --------- beginning of system
12-02 14:36:44.725 16332-16758/com.reading W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.reading/cache
12-02 14:36:44.731 16332-16404/com.reading W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.reading/cache
12-02 14:36:44.759 16332-16332/com.reading W/unknown:React: Packager connection already open, nooping.
12-02 14:36:46.048 16332-19531/com.reading E/ReactNativeJS: Unknown named module: './qiniu/auth/digest.js'
12-02 14:36:46.081 16332-16332/com.reading I/ViewRootImpl: CPU Rendering VSync enable = true
12-02 14:36:46.114 16332-19531/com.reading E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by Richard-Cao** [comment]
这个看 #8，你是Windows机器吧

**Comment by wangfangc** [comment]
恩 是的 是用windows 机器
