### ISSUE TITLE
ios 启动后报错

### ISSUE THREAD

**Issue by bubyday** [attentiveness/reading#54]
![Uploading 屏幕快照 2016-12-28 下午8.06.39.png…]()
ios 启动后报错  请问这个是啥原因呢？

**Comment by Richard-Cao** [comment]
并不能看到图……

**Comment by alansuhe** [comment]
我也遇到启动闪退，报错如下：
`Cannot read property 'on' of undefined
TypeError: Cannot read property 'on' of undefined
    at Client.connect (/Users/appdev/workspace/reading/node_modules/.1.9.0@fb-watchman/index.js:184:14)
    at Client.command (/Users/appdev/workspace/reading/node_modules/.1.9.0@fb-watchman/index.js:228:12)
    at Client.capabilityCheck (/Users/appdev/workspace/reading/node_modules/.1.9.0@fb-watchman/index.js:290:8)
    at WatchmanWatcher.init (/Users/appdev/workspace/reading/node_modules/.1.4.1@sane/src/watchman_watcher.js:173:15)
    at new WatchmanWatcher (/Users/appdev/workspace/reading/node_modules/.1.4.1@sane/src/watchman_watcher.js:40:8)
    at createWatcher (/Users/appdev/workspace/reading/node_modules/.17.0.3@jest-haste-map/build/index.js:536:23)
    at Array.map (native)
    at HasteMap._watch (/Users/appdev/workspace/reading/node_modules/.17.0.3@jest-haste-map/build/index.js:654:44)
    at _buildPromise._buildFileMap.then.then.hasteMap (/Users/appdev/workspace/reading/node_modules/.17.0.3@jest-haste-map/build/index.js:250:21)
    at process._tickCallback (internal/process/next_tick.js:103:7)
~
Process terminated. Press <enter> to close the window

`
不知是不是同样问题

**Comment by Richard-Cao** [comment]
这是watchman出了啥问题么，我没遇到过，，我是mac机器

**Comment by alansuhe** [comment]
我也是mac

**Comment by Richard-Cao** [comment]
这问题应该是你本地环境的问题
